### ISSUE TITLE
CBCT:CUDA:Atb an illegal memory access was encountered

### ISSUE THREAD

**Issue by zzzisGLB** [ShanghaiTech-IMPACT/4DRGS#3]
Hello, your paper is excellent. I think your innovative code is very good. I encountered a problem when I reproduced the code.

(4DRGS) root@4277078b872a:~/4DRGS/TIGRE-2.4/Python# cd /root/4DRGS
export CUDA_LAUNCH_BLOCKING=1
python train.py -m=output/case2_30v_10k -s=./dataset/case2 --Nviews=30 --iteration=10000 --ADC_until_iter=5000
CUDA available: True
Device: NVIDIA GeForce RTX 4090
Optimizing output/case2_30v_10k
Output folder: output/case2_30v_10k [27/05 23:05:53]
Training [27/05 23:05:53]
camera loading: 100%|███████████████████████████████████████████████████| 133/133 [00:00<00:00, 42871.38it/s]
Trainig cameras: [  0   4   8  13  17  22  26  31  35  39  44  48  53  57  62  66  70  75
  79  84  88  93  97 101 106 110 115 119 124 128] [27/05 23:06:02]
Testing cameras: [  1   2   3   5   6   7   9  10  11  12  14  15  16  18  19  20  21  23
  24  25  27  28  29  30  32  33  34  36  37  38  40  41  42  43  45  46
  47  49  50  51  52  54  55  56  58  59  60  61  63  64  65  67  68  69
  71  72  73  74  76  77  78  80  81  82  83  85  86  87  89  90  91  92
  94  95  96  98  99 100 102 103 104 105 107 108 109 111 112 113 114 116
 117 118 120 121 122 123 125 126 127 129 130 131 132] [27/05 23:06:02]
FDK initialization [27/05 23:06:02]
../Common/CUDA/TIGRE_common.cpp (7): Main loop fail 
../Common/CUDA/TIGRE_common.cpp (14): CBCT:CUDA:Atb an illegal memory access was encountered

I can't solve it, hope you can give me some advice

**Comment by Zhentao-Liu** [comment]
@glbisnoob Hi, I also encountered the same problem you mentioned. This is indeed an issue with the TIGRE toolbox. I have now integrated the [LEAP toolbox](https://github.com/LLNL/leap) for FDK reconstruction, and it works without problems. You can follow the instructions in the README or on the [LEAP toolbox page](https://github.com/LLNL/leap) for installation. Hope it goes smoothly for you.

**Comment by glbisnoob** [comment]
Thank you. Following your detailed environment setup instructions, I successfully created the conda environment and can run the code smoothly. Your work is excellent.
